version: "3.3"
services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devdbpassword
      MYSQL_DATABASE: wp
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpressdevdbpassword
    restart: always

  wordpress:
    depends_on:
      - db
    build: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./plugins/kvweb25-blocks:/var/www/html/wp-content/plugins/kvweb25-blocks
      - ./themes/kvweb25-theme:/var/www/html/wp-content/themes/kvweb25-theme
    ports:
      - "8086:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpressdevdbpassword
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        /* development parameters */
        define('WP_CACHE', false);
        define('WP_ENVIRONMENT_TYPE', 'development');
        define('WP_DEBUG_LOG', true);

        /* Mail config */
        define('EEE_SMTP_FROM', 'wordpress@localhost.test');
        define('EEE_SMTP_FROM_NAME', 'local wordpress');
        define('EEE_SMTP_HOST', 'mailhog');
        define('EEE_SMTP_PORT', 1025);
        define('EEE_SMTP_USER', '');
        define('EEE_SMTP_PASS', '');
        define('EEE_SMTP_ENCRYPTION', '');
        define('EEE_FORM_RECIPIENT', 'kontaktformular@localhost.test');

        /* JS Script debug */
        define('SCRIPT_DEBUG', true );
    restart: always
  wp-cli:
    # To execute run: 'docker-wp <command>' ('docker compose run --rm wp-cli')
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    volumes_from:
      - wordpress
    user: 33:33
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpressdevdbpassword
      HOME: /tmp
    # command: tail -f /dev/null
    command: wp
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
volumes:
  db_data: {}
  wordpress:
